DIM SHARED ld(12), v(12), vv(12), vvv(4), vvvv(2), s(12), sd(12), vi(12), dr(12), ho(12), wi(12), wr(12), wo(12), l(12), ll(8), lll(4), lzz(17)
DIM SHARED llll(2), vd(12), gf(12), ga(12), p(12), dgf(12), dga(12), pd(12)
DIM SHARED lm(16), lc(6), vc(6), pc(6), sc(6)
DIM SHARED talg(12), tadv(12), ass(12), ssa(12), mal(12), mla(12), gl(12), lrsarja(100), lrj(100), rmp(100), rmv(100), rpi(100), rsi(100), rjv(100)
DIM SHARED rvo(100), rta(100), rda(100), lrpoff(100), vdd(6), vds(4), vdf(2), vei$(6), veo$(6), ker(12), ldd(6), lds(4), ldf(2), laah(10)
DIM SHARED qwin(8), swin(4), fwin(2), dwin(6), ddwin(4), dddwin(2), dla(6), dl(6), dal(6), ero(20)
DIM SHARED lw(12), vw(12), sw(12), tuurix(12), wx1(12), wx2(12), wx3(12), ms(12)
DIM SHARED lllb(2), vvvb(2), bwin(2), bla(2), bal(2), bl(2)
DIM SHARED leh(20), veh(20), eero(20), ep(20)
DIM SHARED emal(20), emla(20), egl(20), peh(20), seh(20), elt(6)
COMMON SHARED v(), vv(), vvv(), vvvv(), s(), sd(), ld(), vi(), dr(), ho(), wi(), wr(), wo(), l(), ll(), lll()
COMMON SHARED llll(), lamp, lecond, lous, lunko, lut, vd(), gf(), ga(), p(), dgf(), dga(), pd(), lm(), lc(), vc(), pc(), sc()
COMMON SHARED lampm, lousm, lecondm, lunkom, talg(), tadv(), ass(), ssa(), lutm, mal(), mla(), gl()
COMMON SHARED lrsarja(), lrj(), rmp(), rmv(), rpi(), rsi(), rjv(), rvo(), rta(), rda(), lrpoff(), vdd(), vds(), vdf()
COMMON SHARED vei$(), veo$(), ker(), ldd(), lds(), ldf(), lkar, laah(), qwin(), swin(), fwin(), dwin(), ddwin(), dddwin(), dla(), dl(), dal(), ped, sarja, proz, mo, tre, tauti, tauti2, nimi$
COMMON SHARED daulu, kukka, u, pd, dl, dpt, dpv, kr, ki, raha, puoli, pt, pv
COMMON SHARED cheer, yk, mikki, jursi, allgo, pdvo, pdvw, pdvt, pdvl, z, molce
COMMON SHARED dgf, dga, xcup, w, kauzi, halli$, a, b, c, d, e, f, g, h, i, j, k, m
COMMON SHARED ero, ky, tauti3, ralli, jarko, vai, moplus, extra, kausi, valm, hjalli
COMMON SHARED psmo, psmw, psmt, psml, banki, ghalli, gi, dotte, qkr, veikko, oi, veiggo, panos, mesta, memes, hgd, yy, fucka, ducka, jucka, gagga
COMMON SHARED ukka1, ukka2, ukka3, ukka4, ukka5, ukka6, ukka7, ykka1, ykka2, ykka3, ykka4, skr, akka, ukko, aa, bb, cc, dd, ee, ff, gg, hh, fkr
COMMON SHARED mm AS STRING, sopu, palo, hinta, lw(), vw(), sw(), tuurix(), wx1(), wx2(), wx3(), ms(), franko, knhl, unhl
COMMON SHARED assassi, x, lllb(), vvvb(), bwin(), kopo, bla(), bal(), bl(), lonssi, lonssim, tampio, gogo, cacca, veh(), leh()
COMMON SHARED eero(), ep(), e1, e2, e3, e4, e5, e6, euro, edus1, edus2, edus3, eds1, eds2, eds3, ekr
COMMON SHARED emal(), emla(), egl(), peh(), seh(), pvb1, elt()
COMMON SHARED ykka5, ykka6, ykka7, ykka8, dext, lemes, lemesm
COMMON SHARED lamp1, lecond1, lonssi1, lous1, lut1, lunko1, lemes1, leljas
COMMON SHARED lampm1, lecondm1, lonssim1, lousm1, lutm1, lunkom1, lemesm1, carica, lzz()

